### ISSUE TITLE
Install.md

### ISSUE THREAD

**Issue by ahundt** [cpaxton/costar_stack#24]
I'm looking through [install.md](https://github.com/cpaxton/costar_stack/blob/master/INSTALL.md) and it seems the setup manually clones a number of repositories. Is there a vcstool or wstool (forgot which) which provides correct working commit information?

**Comment by ahundt** [comment]
Also I'd like to add a setup script as part of this issue to https://github.com/ahundt/robotics_setup

**Comment by ahundt** [comment]
I'll probably like to configure it to either set up in one of:

- `~/catkin_ws/src`
- `~/src/catkin_ws/src`

**Comment by cpaxton** [comment]
That's the standard place which means it may clash with someone else's ros workspace.

Best,
Chris

Sent from my phone


________________________________

**Comment by ahundt** [comment]
can you clarify... what's the standard practice?

If there is a way to create the setup script such that it is minimally interfering and most likely to work even if someone has an existing setup, I'd appreciate those details.

**Comment by cpaxton** [comment]
Yeah, people are likely to already have a catkin workspace, but you can chain or have multiple -- so it's better to make a costar specific one.

________________________________

**Comment by ahundt** [comment]
okay, but can vcstool or whatever the appropriate thing is be used for a costar specific one?

**Comment by cpaxton** [comment]
To clarify, catkin workspace is normally:
```
/home/$USER/catkin_ws
```

If theirs has any shared third party dependencies with different versions, there might be a clash, so it's better to build in:
```
/home/$USER/costar_ws
```

wstool doesn't solve this problem because the concern is multiple versions.

**Comment by cpaxton** [comment]
yeah we can still use it though

**Comment by ahundt** [comment]
okay, is it this file? Are some things missing?
https://github.com/cpaxton/costar_stack/blob/master/costar.rosinstall

We should also have a master version and create at least 1 release where specific release branches (preferably), tags (also good), or hashes (if completely necessary) are used to produce a known working configuration.

**Comment by cpaxton** [comment]
@ahundt what is the issue here? can we close this?

**Comment by ahundt** [comment]
The issue here is that compatible release versions aren't specified so breakage will eventually occur

**Comment by ahundt** [comment]
I believe this item is still outstanding because we don't have a reliable way of installing the exact configuration we use on the lab workstation... do we? For example this would include all custom patches like in ur_modern_driver, and all other repos.

**Comment by cpaxton** [comment]
@ahundt I added a note about ur modern driver pointing to the correct branch. The rest of our repos are up to date. I use the install.md file extensively to set up CoSTAR on new machines, so I'm happy with this. I also don't have any intention of specifying release versions for the time being. My `install_indigo.sh` script is also reliable and has been tested. What's the problem?

**Comment by cpaxton** [comment]
Closing since no response
