### ISSUE TITLE
instructor accumulated lag

### ISSUE THREAD

**Issue by cpaxton** [cpaxton/costar_stack#33]

**Comment by fjonath1** [comment]
Every time robot action/robot components (move to waypoints, smart moves, etc) is clicked, the memory usage increased by about ~1MB. Other components do not seems to have this effect.

**Comment by cpaxton** [comment]
It must be loading everything from disc again every time. That sounds fixable.

Best,
Chris

Sent from my phone


________________________________

**Comment by fjonath1** [comment]
This issue fixed in commit [5c39533c18d8c36c0d67761d305347f4180e0c96](https://github.com/cpaxton/costar_stack/commit/5c39533c18d8c36c0d67761d305347f4180e0c96).
