### ISSUE TITLE
List of waypoints does not reflects the current available waypoints

### ISSUE THREAD

**Issue by fjonath1** [cpaxton/costar_stack#39]
Ros service: `/costar/GetWaypointsList` does not get updated when we delete a waypoint on waypoint manager, which caused `move to waypoint`, `plan to waypoint`, etc. that uses this service to retain the list of old waypoints that do not exist anymore.

**Comment by cpaxton** [comment]
Got it, that probably means it's not reading from the files again. That part of instructor is really stupid.

Best,
Chris

Sent from my phone


________________________________

**Comment by cpaxton** [comment]
Delete should work: as per PR  #40
