### ISSUE TITLE
Strengthen CoSTAR development processes for future releases.

### ISSUE THREAD

**Issue by ahundt** [cpaxton/costar_stack#53]
I noticed the [1.0.0 release](https://github.com/cpaxton/costar_stack/releases/tag/v1.0.0) I had understood this would be after I've validated the kuka version, and I've already discovered a few bugs. 

Unfortunately, this is also not currently a reproducible release. This really needs sha1 revision info for all dependency repositories. Also the kuka information wasn't ready although we had discussed preparing it for release. The setup scripts weren't tested on a clean system and don't work without modification.

I think all the pre-release processes should be improved upon. There should be build testing, continuous integration, and a milestone plan of what is/isn't to be included in a release since we already have all the issues created it isn't too hard to create a milestone feature with what's expected to be included.

**Comment by cpaxton** [comment]
I'm marking this done. We can make further improvements later, in particularly in the kinetic-devel branch (which does not currently pass).
