### ISSUE TITLE
Robotiq on Kinetic

### ISSUE THREAD

**Issue by cpaxton** [cpaxton/costar_stack#56]

**Comment by ahundt** [comment]
https://github.com/cpaxton/costar_stack/issues/10

we made kinetic-devel and indigo-devel selectable here:
https://github.com/jhu-lcsr/robotiq/tree/kinetic-devel

**Comment by ahundt** [comment]
setup script:
https://github.com/ahundt/robotics_setup/blob/master/costar.sh

**Comment by cpaxton** [comment]
setup script should be in this repo

**Comment by cpaxton** [comment]
and there are no changes in the robotiq package you linked me to

**Comment by ahundt** [comment]
There are definitely changes, look at these:
https://github.com/jhu-lcsr/robotiq/tree/kinetic-devel-merge-jade
https://github.com/jhu-lcsr/robotiq/tree/kinetic-devel
https://github.com/jhu-lcsr/robotiq/tree/jade-devel

Also there weren't branches for each release before.
If kinetic-devel-merge-jade can be tested and works on the robot we should probably use that.

As for the setup script sure I can copy paste it in...
